services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: memorycard_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: memorycard
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - memorycard_network

  # pgAdmin (administrador visual de PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: memorycard_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - memorycard_network

volumes:
  postgres_data:
    name: memorycard_postgres_data

networks:
  memorycard_network:
    name: memorycard_network
    driver: bridge
